In [19]:

import numpy as np
from PIL import Image
image = Image.open('Sample.jpg')
print(image.size)
numpydata = np.asarray(image)
print(numpydata.shape)
image.show()

(800, 533)
(533, 800, 3)


In [33]:
frame = np.round(np.mean(numpydata, axis = 2)/255)*255# + numpydata[:,:,1] + numpydata[:,:,2])/3)
print(frame)
im = Image.fromarray(np.uint8(frame))
im.show()


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [60]:
def tile(arr):
    kernel = (3,3)
    tiled = []
    for i in range(0,len(arr[0]) - kernel[0],kernel[0]):
        row = []
        for j in range(0,len(arr) - kernel[1], kernel[1]):
            row += [np.mean(arr[i:i+kernel[0],j:j+kernel[1]])]
        tiled+=[row]
    return np.uint8(tiled)

In [66]:
t_array = tile(frame)
tiled = Image.fromarray(t_array)
print(t_array.shape)

(266, 177)


In [70]:
tiled.show()
im.show()


(eog:32022): Gtk-CRITICAL **: 23:23:39.224: gtk_cell_area_apply_attributes: assertion 'GTK_IS_CELL_AREA (area)' failed

(eog:32022): Gtk-CRITICAL **: 23:23:39.224: gtk_cell_area_foreach: assertion 'GTK_IS_CELL_AREA (area)' failed

(eog:32022): Gtk-CRITICAL **: 23:23:42.307: gtk_cell_area_apply_attributes: assertion 'GTK_IS_CELL_AREA (area)' failed

(eog:32022): Gtk-CRITICAL **: 23:23:42.307: gtk_cell_area_foreach: assertion 'GTK_IS_CELL_AREA (area)' failed
